# Generated by Django 4.1.2 on 2022-10-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40, unique=True)),
                ('comment', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='test/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
