# Generated by Django 4.1.2 on 2022-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, verbose_name='pk')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='username')),
            ],
        ),
    ]
